### ISSUE TITLE
Возможно не правильная работа вкладки Обработчики. Компонент VirtualPage

### ISSUE THREAD

**Issue by skytmn** [vgrish/virtualpage#2]
Похоже глючит раздел настройки обработчиков, прилагаю скрины
1) http://clip2net.com/s/3ivIc4I тут я создаю новый обработчик типа «Динамический ресурс», задаю ему имя, тип Динамический ресурс, предлагается выбрать по какому шаблону будет генерится видимо, выбираю свой шаблон, и пишу описание, которое я так понял ни где не должно во фронте фигурировать. Сохраняю

2) http://clip2net.com/s/3ivIo1v получаю страницу оформленную в своем шаблоне, но вместо результата работы сниппета, текст описания (?)…

3)Иду снова в обработчики, открываю свой созданный обработчик и там вижу: http://clip2net.com/s/3ivIyGk
где селект запись почему уже не перечень шаблонов а перечень ресурсов сайта.

Кстати пробовал с остальными типами, все так же глючат кроме типа «Ресурс», который работает корректно без проблем.

Может что то не так делаю или не так понял?

**Comment by vgrish** [comment]
fix
