### ISSUE TITLE
Баг с префиксом кэша 

### ISSUE THREAD

**Issue by soulcreate** [vgrish/virtualpage#4]
Не понял как тут создать пулл регвест, вот описание и решение проблемы: https://github.com/soulcreate/virtualpage/pull/1

**Comment by vgrish** [comment]
Понял, поправил https://github.com/vgrish/virtualpage/commit/939f7ee6e24af73c0f0dee9bba7598862b836d49
Спасибо!

**Comment by soulcreate** [comment]
Обнаружил гигабайт(!) ошибок в лог-файле. Оказалось, что нужно сначала подготовить директории с префиксом кэша, а уже затем отдавать их в fastroute.
на 366 строчке файлика `core/components/virtualpage/model/virtualpage/virtualpage.class.php` нужно добавить в условие if `writeTree`:
```
        if (!empty($cachePrefix)) {
            $cachePrefix = '/' . $cachePrefix;
            $this->modx->cacheManager->writeTree($this->modx->getOption(xPDO::OPT_CACHE_PATH) . 'default/' . $this->namespace . $cachePrefix . '/fastroute/');
        }
```

PS: не понимаю как в этот репозиторий исправления через пулл-реквесты вносить
